default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: sample_app_development
  username: sample_app_user
  password: Iefjieaieu8u

test:
  <<: *default
  database: sample_app_test
  username: sample_app_user
  password: Iefjieaieu8u

production:
  <<: *default
  database: sample_app_production
  username: sample_app_user
  password: <%= ENV['HEROKU_TW_DATABASE_PASSWORD'] %>
